name: testiaapi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.2.2
  http: ^1.3.0
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  icons_launcher: ^3.0.0
  chat_gpt_sdk: ^3.1.4


flutter:
  uses-material-design: true
  assets:
   - assets/Noria.png
